// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaNx9BzqQH8mvFszbNRnjI8zo1mqXsGTE',
    appId: '1:339651596321:web:2af869226dabda13769360',
    messagingSenderId: '339651596321',
    projectId: 'smartify-firebase-1b581',
    authDomain: 'smartify-firebase-1b581.firebaseapp.com',
    storageBucket: 'smartify-firebase-1b581.firebasestorage.app',
    measurementId: 'G-SW5PNZJ15F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVgRAB0XymmHVRXrL2GrUYu8tFYUPMoxc',
    appId: '1:339651596321:android:0fe39087c9584114769360',
    messagingSenderId: '339651596321',
    projectId: 'smartify-firebase-1b581',
    storageBucket: 'smartify-firebase-1b581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHnMNXjGiKpijymWxeY1acXYWXC9UFFV8',
    appId: '1:339651596321:ios:7050a9468d1b00e2769360',
    messagingSenderId: '339651596321',
    projectId: 'smartify-firebase-1b581',
    storageBucket: 'smartify-firebase-1b581.firebasestorage.app',
    iosBundleId: 'com.example.smartifyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHnMNXjGiKpijymWxeY1acXYWXC9UFFV8',
    appId: '1:339651596321:ios:7050a9468d1b00e2769360',
    messagingSenderId: '339651596321',
    projectId: 'smartify-firebase-1b581',
    storageBucket: 'smartify-firebase-1b581.firebasestorage.app',
    iosBundleId: 'com.example.smartifyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaNx9BzqQH8mvFszbNRnjI8zo1mqXsGTE',
    appId: '1:339651596321:web:ec751267f25384d9769360',
    messagingSenderId: '339651596321',
    projectId: 'smartify-firebase-1b581',
    authDomain: 'smartify-firebase-1b581.firebaseapp.com',
    storageBucket: 'smartify-firebase-1b581.firebasestorage.app',
    measurementId: 'G-FV4194B4TD',
  );
}
